-- liquibase formatted sql

-- changeset whoiszxl:1
-- comment 初始化评论表数据

select 1;

INSERT INTO `cmt_comment` (`id`, `module`, `obj_id`, `parent_id`, `reply_id`, `member_id`, `avatar`, `username`, `content`, `up_count`, `down_count`, `pic_list`, `hot_status`, `top_status`, `child_comment_count`, `client_ip`, `ip_address`, `version`, `status`, `is_deleted`, `created_by`, `updated_by`, `created_at`, `updated_at`) VALUES (1, 1, 1, 0, 0, 1, 'https://tt-zhipin-oss.oss-cn-shenzhen.aliyuncs.com/image/default2.png', '姜维', '这个视频真不错,给你点赞了!', 0, 0, '', 0, 0, 0, '106.13.7.252', '北京市', 1, 1, 0, '', '', now(), now());
INSERT INTO `cmt_comment` (`id`, `module`, `obj_id`, `parent_id`, `reply_id`, `member_id`, `avatar`, `username`, `content`, `up_count`, `down_count`, `pic_list`, `hot_status`, `top_status`, `child_comment_count`, `client_ip`, `ip_address`, `version`, `status`, `is_deleted`, `created_by`, `updated_by`, `created_at`, `updated_at`) VALUES (2, 1, 1, 0, 0, 1, 'https://tt-zhipin-oss.oss-cn-shenzhen.aliyuncs.com/image/default2.png', '姜维', '看起来确实非常不错，下次还会来看', 0, 0, '', 0, 0, 0, '106.13.7.252', '北京市', 1, 1, 0, '', '', now(), now());
INSERT INTO `cmt_comment` (`id`, `module`, `obj_id`, `parent_id`, `reply_id`, `member_id`, `avatar`, `username`, `content`, `up_count`, `down_count`, `pic_list`, `hot_status`, `top_status`, `child_comment_count`, `client_ip`, `ip_address`, `version`, `status`, `is_deleted`, `created_by`, `updated_by`, `created_at`, `updated_at`) VALUES (3, 1, 1, 0, 0, 1, 'https://tt-zhipin-oss.oss-cn-shenzhen.aliyuncs.com/image/default2.png', '姜维', '666', 0, 0, '', 0, 0, 0, '106.13.7.252', '北京市', 1, 1, 0, '', '', now(), now());
INSERT INTO `cmt_comment` (`id`, `module`, `obj_id`, `parent_id`, `reply_id`, `member_id`, `avatar`, `username`, `content`, `up_count`, `down_count`, `pic_list`, `hot_status`, `top_status`, `child_comment_count`, `client_ip`, `ip_address`, `version`, `status`, `is_deleted`, `created_by`, `updated_by`, `created_at`, `updated_at`) VALUES (4, 1, 1, 0, 0, 1, 'https://tt-zhipin-oss.oss-cn-shenzhen.aliyuncs.com/image/default2.png', '姜维', '非常nice的视频', 0, 0, '', 0, 0, 0, '106.13.7.252', '北京市', 1, 1, 0, '', '', now(), now());
INSERT INTO `cmt_comment` (`id`, `module`, `obj_id`, `parent_id`, `reply_id`, `member_id`, `avatar`, `username`, `content`, `up_count`, `down_count`, `pic_list`, `hot_status`, `top_status`, `child_comment_count`, `client_ip`, `ip_address`, `version`, `status`, `is_deleted`, `created_by`, `updated_by`, `created_at`, `updated_at`) VALUES (5, 1, 1, 0, 0, 1, 'https://tt-zhipin-oss.oss-cn-shenzhen.aliyuncs.com/image/default2.png', '姜维', '好看，喜欢看，下次还会来看', 0, 0, '', 0, 0, 0, '106.13.7.252', '北京市', 1, 1, 0, '', '', now(), now());
INSERT INTO `cmt_comment` (`id`, `module`, `obj_id`, `parent_id`, `reply_id`, `member_id`, `avatar`, `username`, `content`, `up_count`, `down_count`, `pic_list`, `hot_status`, `top_status`, `child_comment_count`, `client_ip`, `ip_address`, `version`, `status`, `is_deleted`, `created_by`, `updated_by`, `created_at`, `updated_at`) VALUES (6, 1, 1, 0, 0, 1, 'https://tt-zhipin-oss.oss-cn-shenzhen.aliyuncs.com/image/default2.png', '姜维', '哈哈哈哈^_^', 0, 0, '', 0, 0, 0, '106.13.7.252', '北京市', 1, 1, 0, '', '', now(), now());
INSERT INTO `cmt_comment` (`id`, `module`, `obj_id`, `parent_id`, `reply_id`, `member_id`, `avatar`, `username`, `content`, `up_count`, `down_count`, `pic_list`, `hot_status`, `top_status`, `child_comment_count`, `client_ip`, `ip_address`, `version`, `status`, `is_deleted`, `created_by`, `updated_by`, `created_at`, `updated_at`) VALUES (7, 1, 1, 0, 0, 1, 'https://tt-zhipin-oss.oss-cn-shenzhen.aliyuncs.com/image/default2.png', '姜维', '来看看', 0, 0, '', 0, 0, 0, '106.13.7.252', '北京市', 1, 1, 0, '', '', now(), now());
INSERT INTO `cmt_comment` (`id`, `module`, `obj_id`, `parent_id`, `reply_id`, `member_id`, `avatar`, `username`, `content`, `up_count`, `down_count`, `pic_list`, `hot_status`, `top_status`, `child_comment_count`, `client_ip`, `ip_address`, `version`, `status`, `is_deleted`, `created_by`, `updated_by`, `created_at`, `updated_at`) VALUES (100, 1, 1, 1, 0, 1, 'https://tt-zhipin-oss.oss-cn-shenzhen.aliyuncs.com/image/default2.png', '姜维', '真的是非常不错的视频!', 0, 0, '', 0, 0, 0, '106.13.7.252', '北京市', 1, 1, 0, '', '', now(), now());
INSERT INTO `cmt_comment` (`id`, `module`, `obj_id`, `parent_id`, `reply_id`, `member_id`, `avatar`, `username`, `content`, `up_count`, `down_count`, `pic_list`, `hot_status`, `top_status`, `child_comment_count`, `client_ip`, `ip_address`, `version`, `status`, `is_deleted`, `created_by`, `updated_by`, `created_at`, `updated_at`) VALUES (101, 1, 1, 1, 100, 1, 'https://tt-zhipin-oss.oss-cn-shenzhen.aliyuncs.com/image/default2.png', '姜维', '大家真是所见略同!', 0, 0, '', 0, 0, 0, '106.13.7.252', '北京市', 1, 1, 0, '', '', now(), now());
INSERT INTO `cmt_comment` (`id`, `module`, `obj_id`, `parent_id`, `reply_id`, `member_id`, `avatar`, `username`, `content`, `up_count`, `down_count`, `pic_list`, `hot_status`, `top_status`, `child_comment_count`, `client_ip`, `ip_address`, `version`, `status`, `is_deleted`, `created_by`, `updated_by`, `created_at`, `updated_at`) VALUES (102, 1, 1, 1, 101, 1, 'https://tt-zhipin-oss.oss-cn-shenzhen.aliyuncs.com/image/default2.png', '姜维', '是的，你说的没错!', 0, 0, '', 0, 0, 0, '106.13.7.252', '北京市', 1, 1, 0, '', '', now(), now());
